# AI Agent to summarize the report
import os
import duckdb
from agno.agent import Agent
from agno.models.google import Gemini
from report import generate_report
from utils import send_email

agent = Agent(
    model= Gemini(id="gemini-2.0-flash", api_key=os.environ.get("GEMINI_API_KEY")),
    tools=[generate_report],
    description="""You are an experienced Analyst that helps people to understand the data they are working with.
                    You are given 4 tables and a question and you analyze the data in a clear and concise way.""",
    instructions="""
                    Read the 'report' generated by the 'generate_report' tool and summarize the main points in a clear and concise way.
                    The summary should include:
                    - The store with the highest total revenue for that day.
                    - The store with the best performance over the last week and last month.
                    - The product with the highest total quantity sold for that day.
                    - The product with the best performance over the last week and last month.
                    - Analysis about the optimized price for each product.
                    - Actionable recommendations for the store and product.
                    If you don't know the answer, you can say 'I don't know'.""",
    expected_output="""A report like response and marketing recommendation for the store and product.""",
    memory=True
)

# Prompt
prompt = "Analyze the tables and return a report like response with totals and marketing recommendation for each store and product."

# Run the agent and get the response
response = agent.run(prompt, markdown=True, stream=False).content

# Send email

recipient_email = os.environ.get("RECIPIENT_EMAIL")
sender_email = os.environ.get("SENDER_EMAIL")
password = os.environ.get("EMAIL_PASSWORD")

# Send the report via email
send_email(recipient_email=recipient_email,
           sender_email=sender_email,
           sender_password=password,
           message=response,
           report_md="report.md",
           charts="mosaic.png"
           )

