import duckdb
import os

# Reading the data
api_data = duckdb.read_parquet(["apidata2025_05_20.parquet", "apidata2025_05_21.parquet"])

########### Generating KPIs from the data ###########
"""
In this section, you will generate the KPIs from the data that wAS extracted from the API.
Let's determine the following KPIs:

By Store:

    1. The total quantity sold of each product
    2. The total revenue generated from each product by store
    3. The total revenue generated by store

By Product:

    1. The total quantity sold of each product
    2. The average price of each product
    3. The average quantity sold of each product
    4. The total revenue generated from each product

"""

# KPIs by store
duckdb.sql("""
        SELECT
           store, 
           product, 
           SUM(quantity) AS total_qty, 
           SUM(price*quantity) AS total_revenue, 
           CAST(date AS DATE) AS dt
        FROM api_data
        GROUP BY store, product, dt
        ORDER BY store, total_qty ASC
           """).show()


# KPIs by product
by_product = duckdb.sql("""
        SELECT 
           product, 
           SUM(quantity) as total_qty,
           AVG(price) as avg_price,
           AVG(quantity) as avg_qty,
           SUM(price*quantity) as total_revenue,
           CAST(date AS DATE) AS dt
        FROM api_data
        GROUP BY product, dt
        ORDER BY total_qty ASC
           """)

by_product.show()